spring.application.name=limits-service
spring.config.import=optional:configserver:http://localhost:8888

spring.profiles.active=qa
spring.cloud.config.profile=qa

#spring.cloud.config.name=

# Server Port Configuration
server.port=8085

# Eureka Discovery Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost

limits-service.minimum=9
limits-service.maximum=991