spring.application.name=naming-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# import configuration from an external Spring Cloud Config Server (running at http://localhost:8888).
#optional:: This means the app wont fail to start if the config server is not available
spring.config.import=optional:configserver:http://localhost:8888